[package]
name = "shpgeo-to-svg"
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[dependencies]
geo-types = "*"
geojson = { version = "*", features = ["geo-types"] }
geo-svg = "0.5.0"
